import type { Template } from "../../../types/builder";

// Template: Festival de Musique
export const festivalTemplate: Template = {
	id: "festival",
	name: "Festival de Musique",
	description: "Template dynamique et coloré pour festivals et concerts",
	category: "evenement",
	thumbnail: "/templates/festival.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#E11D48",
				secondary: "#7C3AED",
				accent: "#FBBF24",
				background: "#0F0F0F",
				text: "#FFFFFF",
				muted: "#9CA3AF",
			},
			typography: {
				headingFont: "Poppins",
				bodyFont: "Inter",
				baseFontSize: 16,
				lineHeight: 1.6,
			},
			spacing: {
				sectionPadding: "spacious",
				containerWidth: "wide",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "gradient",
					gradientFrom: "#E11D48",
					gradientTo: "#7C3AED",
					gradientDirection: "to-bottom-right",
					alignment: "center",
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Devenir Sponsor",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-image",
					imagePosition: "right",
					showTitle: true,
					title: "L'événement musical de l'année",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "timeline-1",
				type: "timeline",
				elementId: "timeline-1",
				visible: true,
				locked: false,
				settings: {
					layout: "alternating",
					showDates: true,
					showIcons: true,
					events: [
						{
							id: "evt-1",
							time: "18:00",
							title: "Ouverture des portes",
							description: "Accueil du public",
							icon: "door-open",
						},
						{
							id: "evt-2",
							time: "19:00",
							title: "Premier concert",
							description: "Artiste en première partie",
							icon: "music",
						},
						{
							id: "evt-3",
							time: "21:00",
							title: "Tête d'affiche",
							description: "Concert principal",
							icon: "star",
						},
						{
							id: "evt-4",
							time: "23:30",
							title: "Afterparty",
							description: "DJ set exclusif",
							icon: "disc",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Choisir",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "tiered",
					columns: 4,
					showNames: true,
					grayscale: false,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "gallery-1",
				type: "gallery",
				elementId: "gallery-1",
				visible: true,
				locked: false,
				settings: {
					layout: "masonry",
					columns: 3,
					gap: "medium",
					images: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "testimonials-1",
				type: "testimonials",
				elementId: "testimonials-1",
				visible: true,
				locked: false,
				settings: {
					layout: "carousel",
					showAvatar: true,
					showCompany: true,
					testimonials: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "cta-1",
				type: "cta",
				elementId: "cta-1",
				visible: true,
				locked: false,
				settings: {
					variant: "banner",
					title: "Rejoignez l'aventure",
					subtitle: "Associez votre marque à un événement inoubliable",
					buttonText: "Devenir partenaire",
					buttonLink: "#contact",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-info",
					showEmail: true,
					showPhone: true,
					showAddress: false,
					showSocials: true,
					formFields: ["name", "email", "company", "message"],
					submitText: "Envoyer ma demande",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Conférence Tech
export const conferenceTemplate: Template = {
	id: "conference",
	name: "Conférence Tech",
	description: "Template professionnel pour conférences et summits",
	category: "professionnel",
	thumbnail: "/templates/conference.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#2563EB",
				secondary: "#1E40AF",
				accent: "#06B6D4",
				background: "#FFFFFF",
				text: "#1E293B",
				muted: "#64748B",
			},
			typography: {
				headingFont: "Inter",
				bodyFont: "Inter",
				baseFontSize: 16,
				lineHeight: 1.7,
			},
			spacing: {
				sectionPadding: "normal",
				containerWidth: "medium",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "minimal",
					alignment: "left",
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Découvrir les offres",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "event-details-1",
				type: "event-details",
				elementId: "event-details-1",
				visible: true,
				locked: false,
				settings: {
					layout: "cards",
					showDate: true,
					showTime: true,
					showLocation: true,
					showOrganizer: true,
					showMap: true,
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-only",
					showTitle: true,
					title: "Pourquoi sponsoriser ?",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "benefits-1",
				type: "benefits",
				elementId: "benefits-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 3,
					showIcons: true,
					iconStyle: "circle",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "team-1",
				type: "team",
				elementId: "team-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showRole: true,
					showBio: true,
					showSocials: true,
					members: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "En savoir plus",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 5,
					showNames: false,
					grayscale: true,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "faq-1",
				type: "faq",
				elementId: "faq-1",
				visible: true,
				locked: false,
				settings: {
					layout: "accordion",
					columns: 1,
					faqs: [
						{
							id: "faq-1",
							question: "Quel est le public attendu ?",
							answer:
								"Nous attendons plus de 500 professionnels du secteur tech.",
						},
						{
							id: "faq-2",
							question: "Quand dois-je confirmer mon sponsoring ?",
							answer:
								"Les inscriptions sont ouvertes jusqu'à 30 jours avant l'événement.",
						},
						{
							id: "faq-3",
							question: "Puis-je personnaliser mon pack ?",
							answer:
								"Oui, nous proposons des offres sur-mesure pour répondre à vos besoins.",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-info",
					showEmail: true,
					showPhone: true,
					showAddress: true,
					showSocials: false,
					formFields: ["name", "email", "company", "phone", "message"],
					submitText: "Nous contacter",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Événement Sportif
export const sportTemplate: Template = {
	id: "sport",
	name: "Événement Sportif",
	description: "Template énergique pour compétitions et événements sportifs",
	category: "sport",
	thumbnail: "/templates/sport.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#16A34A",
				secondary: "#15803D",
				accent: "#F97316",
				background: "#FFFFFF",
				text: "#1F2937",
				muted: "#6B7280",
			},
			typography: {
				headingFont: "Montserrat",
				bodyFont: "Open Sans",
				baseFontSize: 16,
				lineHeight: 1.6,
			},
			spacing: {
				sectionPadding: "spacious",
				containerWidth: "wide",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "image",
					alignment: "center",
					overlayOpacity: 60,
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Soutenir l'événement",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-image",
					imagePosition: "left",
					showTitle: true,
					title: "Une compétition d'exception",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "event-details-1",
				type: "event-details",
				elementId: "event-details-1",
				visible: true,
				locked: false,
				settings: {
					layout: "horizontal",
					showDate: true,
					showTime: true,
					showLocation: true,
					showOrganizer: true,
					showMap: true,
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "timeline-1",
				type: "timeline",
				elementId: "timeline-1",
				visible: true,
				locked: false,
				settings: {
					layout: "horizontal",
					showDates: true,
					showIcons: true,
					events: [
						{
							id: "evt-1",
							time: "08:00",
							title: "Échauffements",
							icon: "activity",
						},
						{
							id: "evt-2",
							time: "10:00",
							title: "Qualifications",
							icon: "flag",
						},
						{
							id: "evt-3",
							time: "14:00",
							title: "Demi-finales",
							icon: "trophy",
						},
						{
							id: "evt-4",
							time: "17:00",
							title: "Grande Finale",
							icon: "medal",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "benefits-1",
				type: "benefits",
				elementId: "benefits-1",
				visible: true,
				locked: false,
				settings: {
					layout: "icons",
					columns: 4,
					showIcons: true,
					iconStyle: "square",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "horizontal",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Devenir sponsor",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "gallery-1",
				type: "gallery",
				elementId: "gallery-1",
				visible: true,
				locked: false,
				settings: {
					layout: "carousel",
					columns: 3,
					gap: "small",
					images: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "tiered",
					columns: 4,
					showNames: true,
					grayscale: false,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "cta-1",
				type: "cta",
				elementId: "cta-1",
				visible: true,
				locked: false,
				settings: {
					variant: "split",
					title: "Prêt à faire équipe ?",
					subtitle: "Associez votre image à l'excellence sportive",
					buttonText: "Contactez-nous",
					buttonLink: "#contact",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-info",
					showEmail: true,
					showPhone: true,
					showAddress: false,
					showSocials: true,
					formFields: ["name", "email", "company", "message"],
					submitText: "Envoyer",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Gala de Charité
export const charityTemplate: Template = {
	id: "charity",
	name: "Gala de Charité",
	description: "Template élégant pour événements caritatifs et galas",
	category: "associatif",
	thumbnail: "/templates/charity.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#9333EA",
				secondary: "#7E22CE",
				accent: "#D946EF",
				background: "#FAFAFA",
				text: "#1E1E1E",
				muted: "#737373",
			},
			typography: {
				headingFont: "Playfair Display",
				bodyFont: "Lato",
				baseFontSize: 17,
				lineHeight: 1.7,
			},
			spacing: {
				sectionPadding: "spacious",
				containerWidth: "medium",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "gradient",
					gradientFrom: "#9333EA",
					gradientTo: "#D946EF",
					gradientDirection: "to-bottom",
					alignment: "center",
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Soutenir la cause",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-only",
					showTitle: true,
					title: "Notre mission",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "benefits-1",
				type: "benefits",
				elementId: "benefits-1",
				visible: true,
				locked: false,
				settings: {
					layout: "list",
					columns: 2,
					showIcons: true,
					iconStyle: "none",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "testimonials-1",
				type: "testimonials",
				elementId: "testimonials-1",
				visible: true,
				locked: false,
				settings: {
					layout: "stacked",
					showAvatar: true,
					showCompany: true,
					testimonials: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "team-1",
				type: "team",
				elementId: "team-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 3,
					showRole: true,
					showBio: true,
					showSocials: false,
					members: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "stacked",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Faire un don",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showNames: true,
					grayscale: false,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "faq-1",
				type: "faq",
				elementId: "faq-1",
				visible: true,
				locked: false,
				settings: {
					layout: "simple",
					columns: 2,
					faqs: [
						{
							id: "faq-1",
							question: "Comment mon don sera-t-il utilisé ?",
							answer: "100% des dons vont directement aux projets soutenus.",
						},
						{
							id: "faq-2",
							question: "Puis-je obtenir un reçu fiscal ?",
							answer: "Oui, un reçu fiscal vous sera envoyé automatiquement.",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "cta-1",
				type: "cta",
				elementId: "cta-1",
				visible: true,
				locked: false,
				settings: {
					variant: "simple",
					title: "Ensemble, faisons la différence",
					subtitle: "Votre soutien compte",
					buttonText: "Devenir mécène",
					buttonLink: "#contact",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-info",
					showEmail: true,
					showPhone: true,
					showAddress: true,
					showSocials: false,
					formFields: ["name", "email", "company", "message"],
					submitText: "Nous contacter",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Corporate Event
export const corporateTemplate: Template = {
	id: "corporate",
	name: "Événement Corporate",
	description: "Template sobre et professionnel pour entreprises",
	category: "professionnel",
	thumbnail: "/templates/corporate.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#1E3A5F",
				secondary: "#2D5A87",
				accent: "#4A90D9",
				background: "#FFFFFF",
				text: "#1A1A1A",
				muted: "#666666",
			},
			typography: {
				headingFont: "Source Sans Pro",
				bodyFont: "Source Sans Pro",
				baseFontSize: 16,
				lineHeight: 1.6,
			},
			spacing: {
				sectionPadding: "normal",
				containerWidth: "medium",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "minimal",
					alignment: "left",
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Découvrir les opportunités",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "event-details-1",
				type: "event-details",
				elementId: "event-details-1",
				visible: true,
				locked: false,
				settings: {
					layout: "vertical",
					showDate: true,
					showTime: true,
					showLocation: true,
					showOrganizer: true,
					showMap: false,
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-image",
					imagePosition: "right",
					showTitle: true,
					title: "À propos de l'événement",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "benefits-1",
				type: "benefits",
				elementId: "benefits-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showIcons: true,
					iconStyle: "none",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Sélectionner",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "team-1",
				type: "team",
				elementId: "team-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showRole: true,
					showBio: false,
					showSocials: true,
					members: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 6,
					showNames: false,
					grayscale: true,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "faq-1",
				type: "faq",
				elementId: "faq-1",
				visible: true,
				locked: false,
				settings: {
					layout: "accordion",
					columns: 1,
					faqs: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-info",
					showEmail: true,
					showPhone: true,
					showAddress: true,
					showSocials: false,
					formFields: ["name", "email", "company", "phone", "message"],
					submitText: "Prendre contact",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Startup / Tech Launch
export const startupTemplate: Template = {
	id: "startup",
	name: "Lancement Startup",
	description: "Template moderne et innovant pour startups tech",
	category: "tech",
	thumbnail: "/templates/startup.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#6366F1",
				secondary: "#4F46E5",
				accent: "#22D3EE",
				background: "#0F172A",
				text: "#F8FAFC",
				muted: "#94A3B8",
			},
			typography: {
				headingFont: "Space Grotesk",
				bodyFont: "Inter",
				baseFontSize: 16,
				lineHeight: 1.6,
			},
			spacing: {
				sectionPadding: "spacious",
				containerWidth: "wide",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "gradient",
					gradientFrom: "#6366F1",
					gradientTo: "#22D3EE",
					gradientDirection: "to-right",
					alignment: "center",
					showDate: true,
					showLocation: false,
					showCta: true,
					ctaText: "Rejoindre l'aventure",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-only",
					showTitle: true,
					title: "Révolutionner l'industrie",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "benefits-1",
				type: "benefits",
				elementId: "benefits-1",
				visible: true,
				locked: false,
				settings: {
					layout: "icons",
					columns: 3,
					showIcons: true,
					iconStyle: "circle",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "timeline-1",
				type: "timeline",
				elementId: "timeline-1",
				visible: true,
				locked: false,
				settings: {
					layout: "vertical",
					showDates: true,
					showIcons: true,
					events: [
						{
							id: "evt-1",
							date: "Q1 2024",
							title: "Seed Round",
							description: "Levée de fonds initiale",
						},
						{
							id: "evt-2",
							date: "Q2 2024",
							title: "MVP Launch",
							description: "Lancement du produit minimum viable",
						},
						{
							id: "evt-3",
							date: "Q4 2024",
							title: "Series A",
							description: "Expansion et croissance",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Investir",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "team-1",
				type: "team",
				elementId: "team-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 3,
					showRole: true,
					showBio: true,
					showSocials: true,
					members: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "testimonials-1",
				type: "testimonials",
				elementId: "testimonials-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					showAvatar: true,
					showCompany: true,
					testimonials: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "cta-1",
				type: "cta",
				elementId: "cta-1",
				visible: true,
				locked: false,
				settings: {
					variant: "banner",
					title: "Construisons le futur ensemble",
					subtitle: "Devenez un partenaire stratégique",
					buttonText: "Parlons-en",
					buttonLink: "#contact",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-only",
					showEmail: true,
					showPhone: false,
					showSocials: true,
					formFields: ["name", "email", "company", "message"],
					submitText: "Envoyer",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Art & Culture
export const artCultureTemplate: Template = {
	id: "art-culture",
	name: "Art & Culture",
	description: "Template créatif pour expositions et événements culturels",
	category: "culture",
	thumbnail: "/templates/art-culture.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#DC2626",
				secondary: "#991B1B",
				accent: "#FBBF24",
				background: "#FFFBEB",
				text: "#1C1917",
				muted: "#78716C",
			},
			typography: {
				headingFont: "Cormorant Garamond",
				bodyFont: "Nunito",
				baseFontSize: 17,
				lineHeight: 1.7,
			},
			spacing: {
				sectionPadding: "spacious",
				containerWidth: "medium",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "image",
					alignment: "center",
					overlayOpacity: 40,
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Découvrir l'exposition",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-image",
					imagePosition: "left",
					showTitle: true,
					title: "L'art au cœur de la ville",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "gallery-1",
				type: "gallery",
				elementId: "gallery-1",
				visible: true,
				locked: false,
				settings: {
					layout: "masonry",
					columns: 3,
					gap: "large",
					images: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "event-details-1",
				type: "event-details",
				elementId: "event-details-1",
				visible: true,
				locked: false,
				settings: {
					layout: "cards",
					showDate: true,
					showTime: true,
					showLocation: true,
					showOrganizer: true,
					showMap: true,
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "team-1",
				type: "team",
				elementId: "team-1",
				visible: true,
				locked: false,
				settings: {
					layout: "carousel",
					columns: 3,
					showRole: true,
					showBio: true,
					showSocials: false,
					members: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "stacked",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Devenir mécène",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showNames: true,
					grayscale: false,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "testimonials-1",
				type: "testimonials",
				elementId: "testimonials-1",
				visible: true,
				locked: false,
				settings: {
					layout: "stacked",
					showAvatar: false,
					showCompany: true,
					testimonials: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-info",
					showEmail: true,
					showPhone: true,
					showAddress: true,
					showSocials: false,
					formFields: ["name", "email", "message"],
					submitText: "Envoyer",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Salon / Foire
export const tradeShowTemplate: Template = {
	id: "trade-show",
	name: "Salon Professionnel",
	description: "Template pour salons, foires et expositions B2B",
	category: "professionnel",
	thumbnail: "/templates/trade-show.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#0891B2",
				secondary: "#0E7490",
				accent: "#F59E0B",
				background: "#FFFFFF",
				text: "#111827",
				muted: "#6B7280",
			},
			typography: {
				headingFont: "Roboto",
				bodyFont: "Roboto",
				baseFontSize: 16,
				lineHeight: 1.6,
			},
			spacing: {
				sectionPadding: "normal",
				containerWidth: "wide",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "image",
					alignment: "left",
					overlayOpacity: 70,
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Exposer au salon",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "event-details-1",
				type: "event-details",
				elementId: "event-details-1",
				visible: true,
				locked: false,
				settings: {
					layout: "horizontal",
					showDate: true,
					showTime: true,
					showLocation: true,
					showOrganizer: true,
					showMap: true,
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-only",
					showTitle: true,
					title: "Le rendez-vous incontournable du secteur",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "benefits-1",
				type: "benefits",
				elementId: "benefits-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showIcons: true,
					iconStyle: "square",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "timeline-1",
				type: "timeline",
				elementId: "timeline-1",
				visible: true,
				locked: false,
				settings: {
					layout: "horizontal",
					showDates: false,
					showIcons: true,
					events: [
						{
							id: "evt-1",
							time: "09:00",
							title: "Ouverture",
							icon: "door-open",
						},
						{ id: "evt-2", time: "10:00", title: "Conférences", icon: "mic" },
						{
							id: "evt-3",
							time: "12:00",
							title: "Networking lunch",
							icon: "users",
						},
						{ id: "evt-4", time: "14:00", title: "Ateliers", icon: "wrench" },
						{ id: "evt-5", time: "18:00", title: "Cocktail", icon: "wine" },
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Réserver un stand",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "tiered",
					columns: 5,
					showNames: true,
					grayscale: false,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "gallery-1",
				type: "gallery",
				elementId: "gallery-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					gap: "small",
					images: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "faq-1",
				type: "faq",
				elementId: "faq-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 2,
					faqs: [
						{
							id: "faq-1",
							question: "Quelle est la surface d'un stand standard ?",
							answer: "Les stands standards font 9m² (3x3m).",
						},
						{
							id: "faq-2",
							question: "Le mobilier est-il inclus ?",
							answer: "Un pack mobilier de base est inclus dans chaque stand.",
						},
						{
							id: "faq-3",
							question: "Puis-je avoir un stand personnalisé ?",
							answer: "Oui, contactez-nous pour les options sur-mesure.",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-info",
					showEmail: true,
					showPhone: true,
					showAddress: true,
					showSocials: false,
					formFields: ["name", "email", "company", "phone", "message"],
					submitText: "Demander un devis",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Hackathon
export const hackathonTemplate: Template = {
	id: "hackathon",
	name: "Hackathon",
	description: "Template dynamique pour hackathons et compétitions de code",
	category: "tech",
	thumbnail: "/templates/hackathon.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#10B981",
				secondary: "#059669",
				accent: "#8B5CF6",
				background: "#111827",
				text: "#F9FAFB",
				muted: "#9CA3AF",
			},
			typography: {
				headingFont: "JetBrains Mono",
				bodyFont: "Inter",
				baseFontSize: 16,
				lineHeight: 1.6,
			},
			spacing: {
				sectionPadding: "spacious",
				containerWidth: "wide",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "gradient",
					gradientFrom: "#10B981",
					gradientTo: "#8B5CF6",
					gradientDirection: "to-bottom-right",
					alignment: "center",
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "Sponsoriser le hackathon",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-only",
					showTitle: true,
					title: "48h pour innover",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "timeline-1",
				type: "timeline",
				elementId: "timeline-1",
				visible: true,
				locked: false,
				settings: {
					layout: "alternating",
					showDates: true,
					showIcons: true,
					events: [
						{
							id: "evt-1",
							date: "Jour 1",
							time: "18:00",
							title: "Kick-off",
							description: "Présentation des challenges",
							icon: "rocket",
						},
						{
							id: "evt-2",
							date: "Jour 1",
							time: "19:00",
							title: "Formation des équipes",
							icon: "users",
						},
						{
							id: "evt-3",
							date: "Jour 2",
							time: "00:00",
							title: "Hacking nocturne",
							icon: "moon",
						},
						{
							id: "evt-4",
							date: "Jour 2",
							time: "12:00",
							title: "Mentorat",
							description: "Sessions avec les experts",
							icon: "help-circle",
						},
						{
							id: "evt-5",
							date: "Jour 2",
							time: "18:00",
							title: "Pitchs finaux",
							icon: "presentation",
						},
						{
							id: "evt-6",
							date: "Jour 2",
							time: "20:00",
							title: "Remise des prix",
							icon: "trophy",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "benefits-1",
				type: "benefits",
				elementId: "benefits-1",
				visible: true,
				locked: false,
				settings: {
					layout: "icons",
					columns: 4,
					showIcons: true,
					iconStyle: "circle",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "horizontal",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: true,
					ctaText: "Devenir sponsor",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "team-1",
				type: "team",
				elementId: "team-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showRole: true,
					showBio: false,
					showSocials: true,
					members: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "tiered",
					columns: 4,
					showNames: true,
					grayscale: false,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "faq-1",
				type: "faq",
				elementId: "faq-1",
				visible: true,
				locked: false,
				settings: {
					layout: "accordion",
					columns: 1,
					faqs: [
						{
							id: "faq-1",
							question: "Combien de participants attendez-vous ?",
							answer: "Nous attendons 200+ développeurs et designers.",
						},
						{
							id: "faq-2",
							question: "Quels sont les thèmes des challenges ?",
							answer:
								"IA, Sustainability, FinTech - les sponsors peuvent proposer leurs propres challenges.",
						},
						{
							id: "faq-3",
							question: "Comment recruter pendant l'événement ?",
							answer:
								"Les packs Gold et Platinum incluent un espace recrutement dédié.",
						},
					],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "cta-1",
				type: "cta",
				elementId: "cta-1",
				visible: true,
				locked: false,
				settings: {
					variant: "banner",
					title: "Recrutez les meilleurs talents tech",
					subtitle: "Associez votre marque à l'innovation",
					buttonText: "Nous contacter",
					buttonLink: "#contact",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-only",
					showEmail: true,
					showPhone: false,
					showSocials: true,
					formFields: ["name", "email", "company", "message"],
					submitText: "Envoyer",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Template: Minimal / Clean
export const minimalTemplate: Template = {
	id: "minimal",
	name: "Minimal",
	description: "Template épuré et minimaliste pour tout type d'événement",
	category: "general",
	thumbnail: "/templates/minimal.png",
	layout: {
		version: "1.0",
		globalStyles: {
			colors: {
				primary: "#18181B",
				secondary: "#27272A",
				accent: "#3B82F6",
				background: "#FAFAFA",
				text: "#18181B",
				muted: "#71717A",
			},
			typography: {
				headingFont: "DM Sans",
				bodyFont: "DM Sans",
				baseFontSize: 16,
				lineHeight: 1.7,
			},
			spacing: {
				sectionPadding: "spacious",
				containerWidth: "narrow",
			},
			customCss: "",
		},
		sections: [
			{
				id: "hero-1",
				type: "hero",
				elementId: "hero-1",
				visible: true,
				locked: false,
				settings: {
					variant: "minimal",
					alignment: "center",
					showDate: true,
					showLocation: true,
					showCta: true,
					ctaText: "En savoir plus",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "about-1",
				type: "about",
				elementId: "about-1",
				visible: true,
				locked: false,
				settings: {
					layout: "text-only",
					showTitle: true,
					title: "Notre vision",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "tiers-1",
				type: "tiers",
				elementId: "tiers-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 3,
					showPrices: true,
					showBenefits: true,
					highlightFeatured: false,
					ctaText: "Choisir",
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "sponsors-1",
				type: "sponsors",
				elementId: "sponsors-1",
				visible: true,
				locked: false,
				settings: {
					layout: "grid",
					columns: 4,
					showNames: false,
					grayscale: true,
					sponsors: [],
				},
				blocks: [],
				customCss: "",
			},
			{
				id: "contact-1",
				type: "contact",
				elementId: "contact-1",
				visible: true,
				locked: false,
				settings: {
					layout: "form-only",
					showEmail: true,
					showPhone: false,
					showSocials: false,
					formFields: ["name", "email", "message"],
					submitText: "Envoyer",
				},
				blocks: [],
				customCss: "",
			},
		],
	},
};

// Export all templates
export const TEMPLATES: Template[] = [
	festivalTemplate,
	conferenceTemplate,
	sportTemplate,
	charityTemplate,
	corporateTemplate,
	startupTemplate,
	artCultureTemplate,
	tradeShowTemplate,
	hackathonTemplate,
	minimalTemplate,
];

// Export template by ID lookup
export const getTemplateById = (id: string): Template | undefined => {
	return TEMPLATES.find((t) => t.id === id);
};

// Export templates by category
export const getTemplatesByCategory = (category: string): Template[] => {
	return TEMPLATES.filter((t) => t.category === category);
};

// Export all categories
export const TEMPLATE_CATEGORIES = [
	{ id: "evenement", name: "Événement", icon: "calendar" },
	{ id: "professionnel", name: "Professionnel", icon: "briefcase" },
	{ id: "sport", name: "Sport", icon: "activity" },
	{ id: "associatif", name: "Associatif", icon: "heart" },
	{ id: "tech", name: "Tech", icon: "cpu" },
	{ id: "culture", name: "Culture", icon: "palette" },
	{ id: "general", name: "Général", icon: "layout" },
];
